import Head from 'next/head'
import Image from 'next/image'
import Intro from '../components/intro'
import Serivces from '../components/services'
import Testimonials from '../components/Testimonials'
import styles from '../styles/Home.module.css'

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Intro />
     <Serivces coWorkers={props.coWorkers} />
     <Testimonials users={props.users} />
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch("https://reqres.in/api/users?page=1");
  const data = await res.json();
  const temp = data.data;
  //push video in json api
  let obj = temp[0];
  const pair = {video:"https://assets.mixkit.co/videos/preview/mixkit-exploring-the-jungle-among-plants-and-palm-trees-32977-large.mp4"};
  obj = {...obj,...pair};
  let coWorkers = temp.filter(item => !item[0]);
  coWorkers[0] = {...obj};
  const res2 = await fetch("https://reqres.in/api/users?page=2");
  const data2 = await res2.json();
  const users =data2.data
  return { props:{ coWorkers,users }};
};
